version: "2"
services:
  booksonic-air:
    image: linuxserver/booksonic-air:2201.1.0
    container_name: booksonic-air
    restart: unless-stopped
    environment:
      - TZ=Europe/London # Specify a timezone to use e.g. Europe/London.
      - PUID=1000
      - PGID=1000
      - CONTEXT_PATH=url-base # Optional base url for use with reverse proxies etc.
    volumes:
      - /host/path/to/podcasts:/podcasts # Podcasts
      - /host/path/to/othermedia:/othermedia # Other media
      - /host/path/to/config:/config # Configuration files.
      - /host/path/to/audiobooks:/audiobooks # Audiobooks
    ports:
      - 4040:4040/tcp # Application WebUI
