version: '3'
services:
  db:
    image: mysql:5.7.38
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Guwei888'
    expose:
      - 3306
    ports:
      - 53306:3306
 
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.0
    container_name: pma
    restart: always
    working_dir:
      /pma
    ports:
      - 62:80
    environment:
      - PMA_PORT=53306
